### ISSUE TITLE
Planning an MVP for frontend views and all necessary information to display

### ISSUE THREAD

**Issue by neysofu** [edgeandnode/graphix#16]
We need to figure out what information we want to display in the frontend views and how.

**Comment by azf20** [comment]
Tracking:
#34 
#35 
#36 
#37

**Comment by fordN** [comment]
I'd say the first priority is unblocking investigation work. 
What is the bare minimum we need in order to support an investigator getting started? They'll need to be able to 1. filter divergences to prioritize investigations, and 2. gather all available debug data for a divergence investigation.

I think we can facilitate productive investigating with the following:
- #35 - At first this can be a simple Grafana panel that facilitates identifying subgraphs and divergence points to investigate
- #37 - A divergence report or generally gathering of divergence information in a usable format for investigators to use

**Comment by azf20** [comment]
That makes sense to me @fordN, and reasonable to prioritise discovery & diagnosis first.

To be clear on terminology, I wanted to confirm my understanding...

- A divergence point is a block for a specific deployment where indexers with the same POI in the prior block then had different POIs (which could be splitting into two or more groups)
- A subgraph with divergent POIs will have at least one, but maybe more divergence points.
- For a given divergence point, there might be several different sets of debug data (at least one per new POI group).
